package dev.mior.esconsultorio.gui.consulta;

import dev.mior.esconsultorio.defaults.Defaults;
import dev.mior.esconsultorio.entity.Consulta;
import dev.mior.esconsultorio.entity.ParcelaPagamento;
import dev.mior.esconsultorio.entity.Servico;
import dev.mior.esconsultorio.util.DialogUtil;
import dev.mior.esconsultorio.util.Imagem;
import java.text.SimpleDateFormat;

/**
 *
 * @author Mior
 */
public class DialogoVisualizarConsulta extends javax.swing.JDialog {

    /** User variables and constants */
    private final Consulta consulta;
    
    /**
     * Creates new form DialogoVisualizarConsulta
     * @param parent
     * @param modal
     * @param consulta
     */
    public DialogoVisualizarConsulta(java.awt.Frame parent, boolean modal, Consulta consulta) {
        super(parent, modal);
        this.consulta = consulta;
        initComponents();
        DialogUtil.addEscapeListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        servicos = org.jdesktop.observablecollections.ObservableCollections.observableList(consulta.getServicos());
        pagamentos = org.jdesktop.observablecollections.ObservableCollections.observableList(consulta.getPagamentos());
        jpGeral = new javax.swing.JPanel();
        jlDataDaConsulta = new javax.swing.JLabel();
        jlHorarioDaConsulta = new javax.swing.JLabel();
        jlCliente = new javax.swing.JLabel();
        jlValorTotalDaConsulta = new javax.swing.JLabel();
        jlValorTotalDosProdutos = new javax.swing.JLabel();
        jlValorTotalDosServicos = new javax.swing.JLabel();
        jtDataDaConsultaValue = new javax.swing.JLabel();
        jlHorarioDaConsultaValue = new javax.swing.JLabel();
        jlClienteValue = new javax.swing.JLabel();
        jlValorTotalDaConsultaValue = new javax.swing.JLabel();
        jlValorTotalDosProdutosValue = new javax.swing.JLabel();
        jlValorTotalDosServicosValue = new javax.swing.JLabel();
        jlObservacoes = new javax.swing.JLabel();
        jlObservacoesValue = new javax.swing.JLabel();
        jpServicos = new javax.swing.JPanel();
        jpListaDeServicos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtServicos = new javax.swing.JTable();
        jpDescricaoServicos = new javax.swing.JPanel();
        jlServicosPrestadosNaConsulta = new javax.swing.JLabel();
        jpPagamentosEEspacador = new javax.swing.JPanel();
        jpEspacador = new javax.swing.JPanel();
        jpPagamentos = new javax.swing.JPanel();
        jpListaDePagamentos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtPagamentos = new javax.swing.JTable();
        jpDescricaoPagamentos = new javax.swing.JPanel();
        jlPagamentosDaConsulta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Informações Da Consulta");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(Imagem.get("info.png"));
        setName("dialogo"); // NOI18N

        jpGeral.setBackground(new java.awt.Color(255, 255, 255));

        jlDataDaConsulta.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jlDataDaConsulta.setText("Data da Consulta:");
        jlDataDaConsulta.setFocusable(false);

        jlHorarioDaConsulta.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jlHorarioDaConsulta.setText("Horário da Consulta:");
        jlHorarioDaConsulta.setFocusable(false);

        jlCliente.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jlCliente.setText("Cliente:");
        jlCliente.setFocusable(false);

        jlValorTotalDaConsulta.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jlValorTotalDaConsulta.setText("Valor total da Consulta:");
        jlValorTotalDaConsulta.setFocusable(false);

        jlValorTotalDosProdutos.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jlValorTotalDosProdutos.setText("Valor total dos Produtos:");
        jlValorTotalDosProdutos.setFocusable(false);

        jlValorTotalDosServicos.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jlValorTotalDosServicos.setText("Valor total dos Serviços:");
        jlValorTotalDosServicos.setFocusable(false);

        jtDataDaConsultaValue.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jtDataDaConsultaValue.setText(SimpleDateFormat.getDateInstance(0, new java.util.Locale("pt", "BR")).format(consulta.getHoraInicial()));
        jtDataDaConsultaValue.setFocusable(false);

        jlHorarioDaConsultaValue.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jlHorarioDaConsultaValue.setText("Das " + Defaults.H_FORMAT.format(consulta.getHoraInicial()) + " às " + Defaults.H_FORMAT.format(consulta.getHoraFinal()));
        jlHorarioDaConsultaValue.setFocusable(false);

        jlClienteValue.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jlClienteValue.setText(consulta.getCliente().getNome());
        jlClienteValue.setFocusable(false);

        jlValorTotalDaConsultaValue.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jlValorTotalDaConsultaValue.setText(checkIfInformed(consulta.getValorTotal()));
        jlValorTotalDaConsultaValue.setFocusable(false);

        jlValorTotalDosProdutosValue.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jlValorTotalDosProdutosValue.setText(checkIfInformed(consulta.getValorProdutos()));
        jlValorTotalDosProdutosValue.setFocusable(false);

        jlValorTotalDosServicosValue.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jlValorTotalDosServicosValue.setText(checkIfInformed(consulta.getValorServicos()));
        jlValorTotalDosServicosValue.setFocusable(false);

        jlObservacoes.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jlObservacoes.setText("Observações:");

        jlObservacoesValue.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jlObservacoesValue.setText(checkIfInformed(brokenString(consulta.getObservacoes(), 90)));

        javax.swing.GroupLayout jpGeralLayout = new javax.swing.GroupLayout(jpGeral);
        jpGeral.setLayout(jpGeralLayout);
        jpGeralLayout.setHorizontalGroup(
            jpGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlObservacoes)
                    .addComponent(jlHorarioDaConsulta)
                    .addComponent(jlDataDaConsulta)
                    .addComponent(jlCliente)
                    .addComponent(jlValorTotalDaConsulta)
                    .addComponent(jlValorTotalDosProdutos)
                    .addComponent(jlValorTotalDosServicos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlValorTotalDaConsultaValue)
                    .addComponent(jlValorTotalDosProdutosValue)
                    .addComponent(jlHorarioDaConsultaValue)
                    .addComponent(jtDataDaConsultaValue)
                    .addComponent(jlValorTotalDosServicosValue)
                    .addComponent(jlClienteValue)
                    .addComponent(jlObservacoesValue))
                .addContainerGap(481, Short.MAX_VALUE))
        );
        jpGeralLayout.setVerticalGroup(
            jpGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtDataDaConsultaValue)
                    .addComponent(jlDataDaConsulta))
                .addGap(18, 18, 18)
                .addGroup(jpGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlHorarioDaConsulta)
                    .addComponent(jlHorarioDaConsultaValue))
                .addGap(18, 18, 18)
                .addGroup(jpGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCliente)
                    .addComponent(jlClienteValue))
                .addGap(18, 18, 18)
                .addGroup(jpGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlValorTotalDaConsulta)
                    .addComponent(jlValorTotalDaConsultaValue))
                .addGap(18, 18, 18)
                .addGroup(jpGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlValorTotalDosProdutos)
                    .addComponent(jlValorTotalDosProdutosValue))
                .addGap(18, 18, 18)
                .addGroup(jpGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlValorTotalDosServicos)
                    .addComponent(jlValorTotalDosServicosValue))
                .addGap(18, 18, 18)
                .addGroup(jpGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlObservacoes)
                    .addComponent(jlObservacoesValue))
                .addGap(18, 18, 18))
        );

        getContentPane().add(jpGeral, java.awt.BorderLayout.PAGE_START);

        jpServicos.setBackground(new java.awt.Color(255, 255, 255));
        jpServicos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpServicos.setLayout(new java.awt.BorderLayout());

        jpListaDeServicos.setBackground(new java.awt.Color(255, 255, 255));
        jpListaDeServicos.setPreferredSize(new java.awt.Dimension(519, 130));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(454, 130));

        jtServicos.setFocusable(false);
        jtServicos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, servicos, jtServicos);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${descricao}"));
        columnBinding.setColumnName("Descrição");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${produtos}"));
        columnBinding.setColumnName("Produtos");
        columnBinding.setColumnClass(java.util.List.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${valor}"));
        columnBinding.setColumnName("Valor");
        columnBinding.setColumnClass(Double.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${produtos}"));
        columnBinding.setColumnName("Valor Produtos");
        columnBinding.setColumnClass(java.util.List.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tipoServico}"));
        columnBinding.setColumnName("Tipo Servico");
        columnBinding.setColumnClass(dev.mior.esconsultorio.entity.TipoServico.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jtServicos);
        if (jtServicos.getColumnModel().getColumnCount() > 0) {
            jtServicos.getColumnModel().getColumn(0).setCellRenderer(new dev.mior.esconsultorio.gui.renderer.AreaDeTextoRenderer());
            jtServicos.getColumnModel().getColumn(1).setCellRenderer(new dev.mior.esconsultorio.gui.renderer.ListaRenderer());
            jtServicos.getColumnModel().getColumn(2).setMinWidth(85);
            jtServicos.getColumnModel().getColumn(2).setPreferredWidth(85);
            jtServicos.getColumnModel().getColumn(2).setMaxWidth(125);
            jtServicos.getColumnModel().getColumn(2).setCellRenderer(new dev.mior.esconsultorio.gui.renderer.DinheiroRenderer());
            jtServicos.getColumnModel().getColumn(3).setMinWidth(85);
            jtServicos.getColumnModel().getColumn(3).setPreferredWidth(85);
            jtServicos.getColumnModel().getColumn(3).setMaxWidth(125);
            jtServicos.getColumnModel().getColumn(3).setCellRenderer(new dev.mior.esconsultorio.gui.renderer.ValorProdutosRenderer());
        }

        javax.swing.GroupLayout jpListaDeServicosLayout = new javax.swing.GroupLayout(jpListaDeServicos);
        jpListaDeServicos.setLayout(jpListaDeServicosLayout);
        jpListaDeServicosLayout.setHorizontalGroup(
            jpListaDeServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        jpListaDeServicosLayout.setVerticalGroup(
            jpListaDeServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpServicos.add(jpListaDeServicos, java.awt.BorderLayout.CENTER);

        jpDescricaoServicos.setBackground(new java.awt.Color(255, 255, 255));

        jlServicosPrestadosNaConsulta.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlServicosPrestadosNaConsulta.setText("Serviços prestados na consulta:");

        javax.swing.GroupLayout jpDescricaoServicosLayout = new javax.swing.GroupLayout(jpDescricaoServicos);
        jpDescricaoServicos.setLayout(jpDescricaoServicosLayout);
        jpDescricaoServicosLayout.setHorizontalGroup(
            jpDescricaoServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDescricaoServicosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlServicosPrestadosNaConsulta)
                .addContainerGap(569, Short.MAX_VALUE))
        );
        jpDescricaoServicosLayout.setVerticalGroup(
            jpDescricaoServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDescricaoServicosLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jlServicosPrestadosNaConsulta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpServicos.add(jpDescricaoServicos, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jpServicos, java.awt.BorderLayout.CENTER);

        jpPagamentosEEspacador.setLayout(new java.awt.BorderLayout());

        jpEspacador.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpEspacadorLayout = new javax.swing.GroupLayout(jpEspacador);
        jpEspacador.setLayout(jpEspacadorLayout);
        jpEspacadorLayout.setHorizontalGroup(
            jpEspacadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
        );
        jpEspacadorLayout.setVerticalGroup(
            jpEspacadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        jpPagamentosEEspacador.add(jpEspacador, java.awt.BorderLayout.PAGE_START);

        jpPagamentos.setBackground(new java.awt.Color(255, 255, 255));
        jpPagamentos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpPagamentos.setLayout(new java.awt.BorderLayout());

        jpListaDePagamentos.setBackground(new java.awt.Color(255, 255, 255));
        jpListaDePagamentos.setPreferredSize(new java.awt.Dimension(519, 130));

        jtPagamentos.setFocusable(false);
        jtPagamentos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, pagamentos, jtPagamentos);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dataEmissao}"));
        columnBinding.setColumnName("Data Emissao");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dataPagamento}"));
        columnBinding.setColumnName("Data Pagamento");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dataVencimento}"));
        columnBinding.setColumnName("Data Vencimento");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${valor}"));
        columnBinding.setColumnName("Valor");
        columnBinding.setColumnClass(Double.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${formaPagamento}"));
        columnBinding.setColumnName("Forma Pagamento");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${parcelaPagamento}"));
        columnBinding.setColumnName("Status do Pagamento");
        columnBinding.setColumnClass(dev.mior.esconsultorio.entity.ParcelaPagamento.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${observacoes}"));
        columnBinding.setColumnName("Observacoes");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane2.setViewportView(jtPagamentos);
        if (jtPagamentos.getColumnModel().getColumnCount() > 0) {
            jtPagamentos.getColumnModel().getColumn(0).setMinWidth(120);
            jtPagamentos.getColumnModel().getColumn(0).setPreferredWidth(120);
            jtPagamentos.getColumnModel().getColumn(0).setMaxWidth(120);
            jtPagamentos.getColumnModel().getColumn(0).setCellRenderer(new dev.mior.esconsultorio.gui.renderer.DataRenderer());
            jtPagamentos.getColumnModel().getColumn(1).setMinWidth(120);
            jtPagamentos.getColumnModel().getColumn(1).setPreferredWidth(120);
            jtPagamentos.getColumnModel().getColumn(1).setMaxWidth(120);
            jtPagamentos.getColumnModel().getColumn(1).setCellRenderer(new dev.mior.esconsultorio.gui.renderer.DataRenderer());
            jtPagamentos.getColumnModel().getColumn(2).setMinWidth(120);
            jtPagamentos.getColumnModel().getColumn(2).setPreferredWidth(120);
            jtPagamentos.getColumnModel().getColumn(2).setMaxWidth(120);
            jtPagamentos.getColumnModel().getColumn(2).setCellRenderer(new dev.mior.esconsultorio.gui.renderer.DataRenderer());
            jtPagamentos.getColumnModel().getColumn(3).setMinWidth(85);
            jtPagamentos.getColumnModel().getColumn(3).setPreferredWidth(85);
            jtPagamentos.getColumnModel().getColumn(3).setMaxWidth(125);
            jtPagamentos.getColumnModel().getColumn(3).setCellRenderer(new dev.mior.esconsultorio.gui.renderer.DinheiroRenderer());
            jtPagamentos.getColumnModel().getColumn(4).setMinWidth(150);
            jtPagamentos.getColumnModel().getColumn(4).setPreferredWidth(150);
            jtPagamentos.getColumnModel().getColumn(4).setMaxWidth(150);
            jtPagamentos.getColumnModel().getColumn(4).setCellRenderer(new dev.mior.esconsultorio.gui.renderer.TextoCentralizadoRenderer());
            jtPagamentos.getColumnModel().getColumn(5).setMinWidth(150);
            jtPagamentos.getColumnModel().getColumn(5).setPreferredWidth(150);
            jtPagamentos.getColumnModel().getColumn(5).setMaxWidth(150);
            jtPagamentos.getColumnModel().getColumn(5).setCellRenderer(new dev.mior.esconsultorio.gui.renderer.StatusPagamentoRenderer());
            jtPagamentos.getColumnModel().getColumn(6).setCellRenderer(new dev.mior.esconsultorio.gui.renderer.AreaDeTextoRenderer());
        }

        javax.swing.GroupLayout jpListaDePagamentosLayout = new javax.swing.GroupLayout(jpListaDePagamentos);
        jpListaDePagamentos.setLayout(jpListaDePagamentosLayout);
        jpListaDePagamentosLayout.setHorizontalGroup(
            jpListaDePagamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        jpListaDePagamentosLayout.setVerticalGroup(
            jpListaDePagamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListaDePagamentosLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jpPagamentos.add(jpListaDePagamentos, java.awt.BorderLayout.CENTER);

        jpDescricaoPagamentos.setBackground(new java.awt.Color(255, 255, 255));

        jlPagamentosDaConsulta.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlPagamentosDaConsulta.setText("Pagamentos da consulta:");

        javax.swing.GroupLayout jpDescricaoPagamentosLayout = new javax.swing.GroupLayout(jpDescricaoPagamentos);
        jpDescricaoPagamentos.setLayout(jpDescricaoPagamentosLayout);
        jpDescricaoPagamentosLayout.setHorizontalGroup(
            jpDescricaoPagamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDescricaoPagamentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlPagamentosDaConsulta)
                .addContainerGap(614, Short.MAX_VALUE))
        );
        jpDescricaoPagamentosLayout.setVerticalGroup(
            jpDescricaoPagamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDescricaoPagamentosLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jlPagamentosDaConsulta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpPagamentos.add(jpDescricaoPagamentos, java.awt.BorderLayout.PAGE_START);

        jpPagamentosEEspacador.add(jpPagamentos, java.awt.BorderLayout.CENTER);

        getContentPane().add(jpPagamentosEEspacador, java.awt.BorderLayout.PAGE_END);

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private String brokenString(String original, int limitCharactersPerLine) {
        if (original == null || original.trim().isEmpty()) return "";
        String brokenedText = "<html>";
        for (int i = 0; i < original.length(); i += limitCharactersPerLine) {
           if (i + limitCharactersPerLine <= original.length()) {
               brokenedText += original.substring(i, i + limitCharactersPerLine) + "<br>";
           } else {
               brokenedText += original.substring(i, original.length());
           }
        }
        brokenedText += "</html>";
        System.out.println("\n\nOriginal: " + original);
        System.out.println("\n\nEdited: " + brokenedText);
        return brokenedText;
    }
    
    private String checkIfInformed(String original) {
        if (original == null || original.trim().isEmpty()) {
            return "<html><i>Não Informado</i></html>";
        } else {
            return original;
        }
    }
        
    private String checkIfInformed(Double original) {
        if (original <= 0) {
            return "<html><i>Não Informado</i></html>";
        } else {
            return Defaults.M_FORMAT.format(original);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlCliente;
    private javax.swing.JLabel jlClienteValue;
    private javax.swing.JLabel jlDataDaConsulta;
    private javax.swing.JLabel jlHorarioDaConsulta;
    private javax.swing.JLabel jlHorarioDaConsultaValue;
    private javax.swing.JLabel jlObservacoes;
    private javax.swing.JLabel jlObservacoesValue;
    private javax.swing.JLabel jlPagamentosDaConsulta;
    private javax.swing.JLabel jlServicosPrestadosNaConsulta;
    private javax.swing.JLabel jlValorTotalDaConsulta;
    private javax.swing.JLabel jlValorTotalDaConsultaValue;
    private javax.swing.JLabel jlValorTotalDosProdutos;
    private javax.swing.JLabel jlValorTotalDosProdutosValue;
    private javax.swing.JLabel jlValorTotalDosServicos;
    private javax.swing.JLabel jlValorTotalDosServicosValue;
    private javax.swing.JPanel jpDescricaoPagamentos;
    private javax.swing.JPanel jpDescricaoServicos;
    private javax.swing.JPanel jpEspacador;
    private javax.swing.JPanel jpGeral;
    private javax.swing.JPanel jpListaDePagamentos;
    private javax.swing.JPanel jpListaDeServicos;
    private javax.swing.JPanel jpPagamentos;
    private javax.swing.JPanel jpPagamentosEEspacador;
    private javax.swing.JPanel jpServicos;
    private javax.swing.JLabel jtDataDaConsultaValue;
    private javax.swing.JTable jtPagamentos;
    private javax.swing.JTable jtServicos;
    private java.util.List<ParcelaPagamento> pagamentos;
    private java.util.List<Servico> servicos;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}