package dev.mior.esconsultorio.gui.cliente;

import dev.mior.esconsultorio.dao.EntityDAO;
import dev.mior.esconsultorio.entity.Cliente;
import dev.mior.esconsultorio.entity.Consulta;
import dev.mior.esconsultorio.gui.consulta.DialogoSalvarConsulta;
import dev.mior.esconsultorio.gui.consulta.DialogoVisualizarConsulta;
import dev.mior.esconsultorio.util.DialogUtil;
import dev.mior.esconsultorio.util.Logger;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.Date;
import javax.persistence.Query;
import javax.persistence.TemporalType;
import javax.swing.JOptionPane;

/**
 *
 * @author Mior
 */
public class DialogoConultarHistoricoDoCliente extends javax.swing.JDialog {

    /** User variables and constants */
    private Cliente cliente;
    private static final EntityDAO<Consulta> DAO = new EntityDAO<>(Consulta.class);

    /**
     * Creates new form DialogoHistoricoDeConsultas
     * @param parent
     * @param modal
     */
    public DialogoConultarHistoricoDoCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        DialogUtil.addEscapeListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = EntityDAO.EMF.createEntityManager();
        consultas = org.jdesktop.observablecollections.ObservableCollections.observableList(new ArrayList<>());
        jpBuscarCliente = new javax.swing.JPanel();
        jlCliente = new javax.swing.JLabel();
        jtfCliente = new javax.swing.JTextField();
        jbtnBuscarCliente = new javax.swing.JButton();
        jlPeriodo = new javax.swing.JLabel();
        jdpPeriodoInicial = new org.jdesktop.swingx.JXDatePicker();
        jlAte = new javax.swing.JLabel();
        jdpPeriodoFinal = new org.jdesktop.swingx.JXDatePicker();
        jcbTodoPeriodo = new javax.swing.JCheckBox();
        jbtnBuscar = new javax.swing.JButton();
        jpHistoricoDoCliente = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        jtConsultas = new javax.swing.JTable();
        jpBotoes = new javax.swing.JPanel();
        jbtnApagar = new javax.swing.JToggleButton();
        jbtnEditarConsulta = new javax.swing.JToggleButton();
        jbtnVisualizarConsulta = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Histórico de Consultas do Cliente");
        setBackground(new java.awt.Color(255, 255, 255));
        setName("dialogo"); // NOI18N

        jpBuscarCliente.setBackground(new java.awt.Color(255, 255, 255));

        jlCliente.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlCliente.setText("Cliente:");

        jtfCliente.setEditable(false);
        jtfCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfCliente.setMargin(new java.awt.Insets(2, 1, 2, 1));

        jbtnBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/find.png"))); // NOI18N
        jbtnBuscarCliente.setToolTipText("Buscar Cliente Cadastrado");
        jbtnBuscarCliente.setFocusPainted(false);
        jbtnBuscarCliente.setFocusable(false);
        jbtnBuscarCliente.setMargin(new java.awt.Insets(2, 4, 1, 4));
        jbtnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarClienteActionPerformed(evt);
            }
        });

        jlPeriodo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlPeriodo.setText("Período:   De");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jcbTodoPeriodo, org.jdesktop.beansbinding.ELProperty.create("${!selected}"), jdpPeriodoInicial, org.jdesktop.beansbinding.BeanProperty.create("editable"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jcbTodoPeriodo, org.jdesktop.beansbinding.ELProperty.create("${!selected}"), jdpPeriodoInicial, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jlAte.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlAte.setText("até");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jcbTodoPeriodo, org.jdesktop.beansbinding.ELProperty.create("${!selected}"), jdpPeriodoFinal, org.jdesktop.beansbinding.BeanProperty.create("editable"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jcbTodoPeriodo, org.jdesktop.beansbinding.ELProperty.create("${!selected}"), jdpPeriodoFinal, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jcbTodoPeriodo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jcbTodoPeriodo.setSelected(true);
        jcbTodoPeriodo.setText("Todo o Período");
        jcbTodoPeriodo.setFocusPainted(false);
        jcbTodoPeriodo.setFocusable(false);

        jbtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/find.png"))); // NOI18N
        jbtnBuscar.setMnemonic('B');
        jbtnBuscar.setText("Buscar");
        jbtnBuscar.setToolTipText("Efetuar busca");
        jbtnBuscar.setFocusPainted(false);
        jbtnBuscar.setFocusable(false);
        jbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBuscarClienteLayout = new javax.swing.GroupLayout(jpBuscarCliente);
        jpBuscarCliente.setLayout(jpBuscarClienteLayout);
        jpBuscarClienteLayout.setHorizontalGroup(
            jpBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBuscarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnBuscarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlPeriodo)
                .addGap(3, 3, 3)
                .addComponent(jdpPeriodoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jlAte)
                .addGap(4, 4, 4)
                .addComponent(jdpPeriodoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbTodoPeriodo)
                .addGap(18, 18, 18)
                .addComponent(jbtnBuscar)
                .addContainerGap(215, Short.MAX_VALUE))
        );
        jpBuscarClienteLayout.setVerticalGroup(
            jpBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBuscarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlCliente)
                        .addComponent(jtfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtnBuscarCliente)
                    .addGroup(jpBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlPeriodo)
                        .addComponent(jdpPeriodoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlAte)
                        .addComponent(jdpPeriodoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcbTodoPeriodo)
                        .addComponent(jbtnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jpBuscarCliente, java.awt.BorderLayout.PAGE_START);

        jpHistoricoDoCliente.setBackground(new java.awt.Color(255, 255, 255));

        jtConsultas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtConsultas.getTableHeader().setReorderingAllowed(false);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, consultas, jtConsultas);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${horaInicial}"));
        columnBinding.setColumnName("Data");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${horaInicial}"));
        columnBinding.setColumnName("Hora Inicial");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${horaFinal}"));
        columnBinding.setColumnName("Hora Final");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${valor}"));
        columnBinding.setColumnName("Valor");
        columnBinding.setColumnClass(Double.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${servicosPrestados}"));
        columnBinding.setColumnName("Servicos Prestados");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${observacoes}"));
        columnBinding.setColumnName("Observacoes");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane.setViewportView(jtConsultas);
        if (jtConsultas.getColumnModel().getColumnCount() > 0) {
            jtConsultas.getColumnModel().getColumn(0).setMinWidth(80);
            jtConsultas.getColumnModel().getColumn(0).setPreferredWidth(80);
            jtConsultas.getColumnModel().getColumn(0).setMaxWidth(80);
            jtConsultas.getColumnModel().getColumn(0).setCellRenderer(new dev.mior.esconsultorio.gui.renderer.DataRenderer());
            jtConsultas.getColumnModel().getColumn(1).setMinWidth(80);
            jtConsultas.getColumnModel().getColumn(1).setPreferredWidth(80);
            jtConsultas.getColumnModel().getColumn(1).setMaxWidth(80);
            jtConsultas.getColumnModel().getColumn(1).setCellRenderer(new dev.mior.esconsultorio.gui.renderer.HorarioRenderer());
            jtConsultas.getColumnModel().getColumn(2).setMinWidth(80);
            jtConsultas.getColumnModel().getColumn(2).setPreferredWidth(80);
            jtConsultas.getColumnModel().getColumn(2).setMaxWidth(80);
            jtConsultas.getColumnModel().getColumn(2).setCellRenderer(new dev.mior.esconsultorio.gui.renderer.HorarioRenderer());
            jtConsultas.getColumnModel().getColumn(3).setMinWidth(150);
            jtConsultas.getColumnModel().getColumn(3).setPreferredWidth(150);
            jtConsultas.getColumnModel().getColumn(3).setMaxWidth(150);
            jtConsultas.getColumnModel().getColumn(3).setCellRenderer(new dev.mior.esconsultorio.gui.renderer.DinheiroRenderer());
            jtConsultas.getColumnModel().getColumn(4).setCellRenderer(new dev.mior.esconsultorio.gui.renderer.AreaDeTextoRenderer());
            jtConsultas.getColumnModel().getColumn(5).setCellRenderer(new dev.mior.esconsultorio.gui.renderer.AreaDeTextoRenderer());
        }

        javax.swing.GroupLayout jpHistoricoDoClienteLayout = new javax.swing.GroupLayout(jpHistoricoDoCliente);
        jpHistoricoDoCliente.setLayout(jpHistoricoDoClienteLayout);
        jpHistoricoDoClienteLayout.setHorizontalGroup(
            jpHistoricoDoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1076, Short.MAX_VALUE)
        );
        jpHistoricoDoClienteLayout.setVerticalGroup(
            jpHistoricoDoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );

        getContentPane().add(jpHistoricoDoCliente, java.awt.BorderLayout.CENTER);

        jpBotoes.setBackground(new java.awt.Color(255, 255, 255));
        jpBotoes.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 15));

        jbtnApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/delete.png"))); // NOI18N
        jbtnApagar.setMnemonic('A');
        jbtnApagar.setText("Apagar Consulta");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jtConsultas, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jbtnApagar, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jbtnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnApagarActionPerformed(evt);
            }
        });
        jpBotoes.add(jbtnApagar);

        jbtnEditarConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/edit.png"))); // NOI18N
        jbtnEditarConsulta.setMnemonic('E');
        jbtnEditarConsulta.setText("Editar Consulta");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jtConsultas, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jbtnEditarConsulta, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jbtnEditarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditarConsultaActionPerformed(evt);
            }
        });
        jpBotoes.add(jbtnEditarConsulta);

        jbtnVisualizarConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/info.png"))); // NOI18N
        jbtnVisualizarConsulta.setMnemonic('V');
        jbtnVisualizarConsulta.setText("Visualizar Consulta");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jtConsultas, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jbtnVisualizarConsulta, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jbtnVisualizarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVisualizarConsultaActionPerformed(evt);
            }
        });
        jpBotoes.add(jbtnVisualizarConsulta);

        getContentPane().add(jpBotoes, java.awt.BorderLayout.PAGE_END);

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private Query createQuery(String sql, Date periodoInicial, Date periodoFinal) {
        Query query = entityManager.createQuery(sql);
        if (periodoInicial != null) query.setParameter("periodoInicial", periodoInicial, TemporalType.TIMESTAMP);
        if (periodoFinal != null) query.setParameter("periodoFinal", periodoFinal, TemporalType.TIMESTAMP);
        return query;
    }
    
    private void jbtnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarClienteActionPerformed
        new DialogoBuscarCliente((Frame) getParent(), true, (c) -> {
            this.cliente = c;
            this.jtfCliente.setText(c.getNome());
        }).setVisible(true);    }//GEN-LAST:event_jbtnBuscarClienteActionPerformed

    private void jbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarActionPerformed
        if (cliente == null) {
            JOptionPane.showMessageDialog(this, "Você deve informar o cliente para poder efetuar a busca!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String sql = "SELECT c FROM Consulta c WHERE c.cliente.id = " + cliente.getId();
        Query query;
        if (!jcbTodoPeriodo.isSelected()) {
            Date periodoInicial = jdpPeriodoInicial.getDate();
            Date periodoFinal = jdpPeriodoFinal.getDate();
            if (periodoFinal != null && periodoInicial != null) {
                if (periodoInicial.getTime() > periodoFinal.getTime()) {
                    JOptionPane.showMessageDialog(this, "Os periodos não podem ser inconsistentes.\nO periodo final esta vindo antes do inicial!", "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                } else {
                    sql += " and c.horaInicial > :periodoInicial and c.horaFinal < :periodoFinal";
                }
            } else if (periodoInicial != null) {
                sql += " and c.horaInicial > :periodoInicial";
            } else if (periodoFinal != null) {
                sql += " and c.horaFinal < :periodoFinal";
            } else {
                JOptionPane.showMessageDialog(this, "Você deve informar o período para poder efeutar a busca!\nCaso não queira selecione a opção \"Todo o Período\".", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
            query = createQuery(sql, periodoInicial, periodoFinal);
        } else {
            query = createQuery(sql, null, null);
        }
        consultas.clear();
        consultas.addAll(query.getResultList());
    }//GEN-LAST:event_jbtnBuscarActionPerformed

    private void jbtnVisualizarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVisualizarConsultaActionPerformed
        new DialogoVisualizarConsulta((Frame) getParent(), true, consultas.get(jtConsultas.getSelectedRow())).setVisible(true);
    }//GEN-LAST:event_jbtnVisualizarConsultaActionPerformed

    private void jbtnEditarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditarConsultaActionPerformed
        int index = jtConsultas.getSelectedRow();
        new DialogoSalvarConsulta((Frame) getParent(), true, (c) -> {
            consultas.set(index, c);
        }, consultas.get(index)).setVisible(true);
    }//GEN-LAST:event_jbtnEditarConsultaActionPerformed

    private void jbtnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnApagarActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Deseja realmente apagar esta consulta?", "Confirmação", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            try {
                Consulta c = consultas.get(jtConsultas.getSelectedRow());
                consultas.remove(c);
                DAO.destroy(c);
            } catch (Exception e) {
                Logger.save(e);
                JOptionPane.showMessageDialog(this, "Não foi possível apagar a consulta!", "Erro Interno", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbtnApagarActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<Consulta> consultas;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JToggleButton jbtnApagar;
    private javax.swing.JButton jbtnBuscar;
    private javax.swing.JButton jbtnBuscarCliente;
    private javax.swing.JToggleButton jbtnEditarConsulta;
    private javax.swing.JToggleButton jbtnVisualizarConsulta;
    private javax.swing.JCheckBox jcbTodoPeriodo;
    private org.jdesktop.swingx.JXDatePicker jdpPeriodoFinal;
    private org.jdesktop.swingx.JXDatePicker jdpPeriodoInicial;
    private javax.swing.JLabel jlAte;
    private javax.swing.JLabel jlCliente;
    private javax.swing.JLabel jlPeriodo;
    private javax.swing.JPanel jpBotoes;
    private javax.swing.JPanel jpBuscarCliente;
    private javax.swing.JPanel jpHistoricoDoCliente;
    private javax.swing.JTable jtConsultas;
    private javax.swing.JTextField jtfCliente;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    
}