package dev.mior.esconsultorio.gui.login;

import dev.mior.esconsultorio.dao.EntityDAO;
import dev.mior.esconsultorio.entity.Consultorio;
import dev.mior.esconsultorio.gui.FramePrincipal;
import dev.mior.esconsultorio.util.Criptografar;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;

/**
 *
 * @author Mior
 */
public class FrameDeLogin extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    
    public FrameDeLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        painel = new javax.swing.JPanel();
        jlUsuario = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jlSenha = new javax.swing.JLabel();
        jtfSenha = new javax.swing.JPasswordField();
        jbtnEntrar = new javax.swing.JButton();
        jlErroUsuario = new javax.swing.JLabel();
        jlErroSenha = new javax.swing.JLabel();
        jlEsqueciMinhaSenha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(dev.mior.esconsultorio.defaults.Defaults.NAME);
        setIconImage(dev.mior.esconsultorio.defaults.Defaults.ICON);
        setName(""); // NOI18N
        setResizable(false);

        painel.setMaximumSize(new java.awt.Dimension(400, 300));
        painel.setMinimumSize(new java.awt.Dimension(400, 300));
        painel.setPreferredSize(new java.awt.Dimension(400, 300));
        painel.setLayout(new java.awt.GridBagLayout());

        jlUsuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jlUsuario.setText("E-Mail");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        painel.add(jlUsuario, gridBagConstraints);

        jtfUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfUsuario.setMargin(new java.awt.Insets(2, 1, 2, 1));
        jtfUsuario.setMinimumSize(new java.awt.Dimension(150, 23));
        jtfUsuario.setPreferredSize(new java.awt.Dimension(150, 23));
        jtfUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfUsuarioKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        painel.add(jtfUsuario, gridBagConstraints);

        jlSenha.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jlSenha.setText("Senha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        painel.add(jlSenha, gridBagConstraints);

        jtfSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfSenha.setMargin(new java.awt.Insets(2, 1, 2, 1));
        jtfSenha.setMinimumSize(new java.awt.Dimension(150, 23));
        jtfSenha.setPreferredSize(new java.awt.Dimension(150, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        painel.add(jtfSenha, gridBagConstraints);

        jbtnEntrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/login.png"))); // NOI18N
        jbtnEntrar.setText(" ENTRAR");
        jbtnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnEntrar.setFocusPainted(false);
        jbtnEntrar.setFocusable(false);
        jbtnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEntrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        painel.add(jbtnEntrar, gridBagConstraints);

        jlErroUsuario.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jlErroUsuario.setForeground(new java.awt.Color(255, 51, 51));
        jlErroUsuario.setText(" ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 0, 0);
        painel.add(jlErroUsuario, gridBagConstraints);

        jlErroSenha.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jlErroSenha.setForeground(new java.awt.Color(255, 51, 51));
        jlErroSenha.setText(" ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 0, 0);
        painel.add(jlErroSenha, gridBagConstraints);

        jlEsqueciMinhaSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlEsqueciMinhaSenha.setText("ESQUECI MINHA SENHA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        painel.add(jlEsqueciMinhaSenha, gridBagConstraints);

        getContentPane().add(painel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnEntrarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jbtnEntrarActionPerformed
        String usuario = jtfUsuario.getText().trim();
        String senha = new String(jtfSenha.getPassword());
        boolean erro = false;
        
        // Verificando se o campo do usuario foi preenchido
        if (usuario.isEmpty()) {
            jlErroUsuario.setText("Preencha este campo!");
            erro = true;
        } else if (!jlErroUsuario.getText().isEmpty()) {
            jlErroUsuario.setText(" ");
        }
        
        // Verificando se o campo da senha foi preenchido
        if (senha.isEmpty()) {
            jlErroSenha.setText("Preencha este campo!");
            erro = true;
        } else if (senha.length() < 6) {
            jlErroSenha.setText("<html>A senha deve conter no mínimo 6<br>caracteres.</html>");
            erro = true;
        } else if (!jlErroSenha.getText().isEmpty()) {
            jlErroSenha.setText(" ");
        }
        
        // Caso ocora algum erro então paramos por aqui...
        if (erro) return;
        
        // Validando o usuario
        if (!consultorio.getUsuario().equals(usuario)) {
            jlErroUsuario.setText("Usuário ou senha inválidos.");
            return;
        }
        
        // Validando a senha
        if (!consultorio.getSenha().equals(Criptografar.MD5(senha))) {
            jlErroUsuario.setText("Usuário ou senha inválidos.");
            return;
        }
        
        // Entrando no sistema
        new FramePrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnEntrarActionPerformed

    private void jtfUsuarioKeyTyped(KeyEvent evt) {//GEN-FIRST:event_jtfUsuarioKeyTyped
        if (jtfUsuario.getText().length() >=  32) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfUsuarioKeyTyped

    // Dao
    private final Consultorio consultorio = new EntityDAO<>(Consultorio.class).findEntities().get(0);

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnEntrar;
    private javax.swing.JLabel jlErroSenha;
    private javax.swing.JLabel jlErroUsuario;
    private javax.swing.JLabel jlEsqueciMinhaSenha;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JPasswordField jtfSenha;
    private javax.swing.JTextField jtfUsuario;
    private javax.swing.JPanel painel;
    // End of variables declaration//GEN-END:variables

}