package dev.mior.esconsultorio.gui.login;

import dev.mior.esconsultorio.dao.EntityDAO;
import dev.mior.esconsultorio.entity.Consultorio;
import java.awt.event.KeyEvent;

/**
 *
 * @author Mior
 */
public class FrameDeRecuperacaoDeSenha extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    
    public FrameDeRecuperacaoDeSenha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        painel = new javax.swing.JPanel();
        jlUsuario = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jbtnEntrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(dev.mior.esconsultorio.defaults.Defaults.NAME);
        setIconImage(dev.mior.esconsultorio.defaults.Defaults.ICON);
        setName(""); // NOI18N
        setResizable(false);

        painel.setMaximumSize(new java.awt.Dimension(400, 300));
        painel.setMinimumSize(new java.awt.Dimension(400, 300));
        painel.setPreferredSize(new java.awt.Dimension(400, 300));
        painel.setLayout(new java.awt.GridBagLayout());

        jlUsuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jlUsuario.setText("E-Mail");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        painel.add(jlUsuario, gridBagConstraints);

        jtfUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfUsuario.setMargin(new java.awt.Insets(2, 1, 2, 1));
        jtfUsuario.setMinimumSize(new java.awt.Dimension(150, 23));
        jtfUsuario.setPreferredSize(new java.awt.Dimension(150, 23));
        jtfUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfUsuarioKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        painel.add(jtfUsuario, gridBagConstraints);

        jbtnEntrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnEntrar.setText("RECUPERAR");
        jbtnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnEntrar.setFocusPainted(false);
        jbtnEntrar.setFocusable(false);
        jbtnEntrar.setMaximumSize(new java.awt.Dimension(140, 31));
        jbtnEntrar.setMinimumSize(new java.awt.Dimension(140, 31));
        jbtnEntrar.setPreferredSize(new java.awt.Dimension(140, 31));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        painel.add(jbtnEntrar, gridBagConstraints);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("CANCELAR");
        jButton1.setMaximumSize(new java.awt.Dimension(140, 31));
        jButton1.setMinimumSize(new java.awt.Dimension(140, 31));
        jButton1.setPreferredSize(new java.awt.Dimension(140, 31));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        painel.add(jButton1, gridBagConstraints);

        getContentPane().add(painel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfUsuarioKeyTyped(KeyEvent evt) {//GEN-FIRST:event_jtfUsuarioKeyTyped
        if (jtfUsuario.getText().length() >=  32) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfUsuarioKeyTyped

    // Dao
    private final Consultorio consultorio = new EntityDAO<>(Consultorio.class).findEntities().get(0);

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jbtnEntrar;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JTextField jtfUsuario;
    private javax.swing.JPanel painel;
    // End of variables declaration//GEN-END:variables

}