package dev.mior.esconsultorio.gui.produto;

import dev.mior.esconsultorio.dao.EntityDAO;
import dev.mior.esconsultorio.entity.Produto;
import dev.mior.esconsultorio.entity.TipoProduto;
import dev.mior.esconsultorio.util.DialogUtil;
import dev.mior.esconsultorio.util.Logger;
import dev.mior.esconsultorio.util.Validar;
import java.awt.Frame;
import java.util.function.Consumer;
import javax.swing.JOptionPane;

/**
 *
 * @author Mior
 */
public class DialogoSalvarProduto extends javax.swing.JDialog {

    /** User variables and constants */
    private Produto produto;
    private TipoProduto tipoProduto;
    private boolean cadastrar = false;
    private final Consumer<Produto> action;
    private static final EntityDAO<Produto> DAO = new EntityDAO<>(Produto.class);
    
    /**
     * Creates new form DialogoSalvarProduto
     * @param parent
     * @param modal
     * @param action
     */
    public DialogoSalvarProduto(java.awt.Frame parent, boolean modal, Consumer<Produto> action) {
        super(parent, modal);
        this.action = action;
        this.cadastrar = true;
        initComponents();
        DialogUtil.addEscapeListener(this);
    }
    
    /**
     * Creates new form DialogoSalvarProduto
     * @param parent
     * @param modal
     * @param action
     * @param produto
     */
    public DialogoSalvarProduto(java.awt.Frame parent, boolean modal, Consumer<Produto> action, Produto produto) {
        super(parent, modal);
        this.action = action;
        this.produto = produto;
        this.cadastrar = false;
        initComponents();
        initProduto();
        DialogUtil.addEscapeListener(this);
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpGeral = new javax.swing.JPanel();
        jlTipoDoProduto = new javax.swing.JLabel();
        jlValor = new javax.swing.JLabel();
        jlDescricaoDoProduto = new javax.swing.JLabel();
        jtfTipoProduto = new javax.swing.JTextField();
        jtfValor = new javax.swing.JFormattedTextField();
        jbtnBuscarTipoProduto = new javax.swing.JButton();
        jbtnNovoTipoProduto = new javax.swing.JButton();
        jtfDescricao = new javax.swing.JTextField();
        jpConfirmar = new javax.swing.JPanel();
        jbtnSalvar = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(cadastrar ? "Cadastrar Novo Produto" : "Editar dados do Produto");
        setBackground(new java.awt.Color(255, 255, 255));
        setName("dialogo"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jpGeral.setBackground(new java.awt.Color(255, 255, 255));

        jlTipoDoProduto.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlTipoDoProduto.setText("Tipo do Produto:");

        jlValor.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlValor.setText("Valor:");

        jlDescricaoDoProduto.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlDescricaoDoProduto.setText("Descrição do Produto:");

        jtfTipoProduto.setEditable(false);
        jtfTipoProduto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfTipoProduto.setToolTipText("Tipo do Produto");
        jtfTipoProduto.setMargin(new java.awt.Insets(2, 1, 2, 1));

        jtfValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jtfValor.setToolTipText("Valor do Produto");
        jtfValor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfValor.setMargin(new java.awt.Insets(2, 1, 2, 1));
        jtfValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfValorKeyTyped(evt);
            }
        });

        jbtnBuscarTipoProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/find.png"))); // NOI18N
        jbtnBuscarTipoProduto.setToolTipText("Buscar Tipo de Produto Cadastrado");
        jbtnBuscarTipoProduto.setFocusPainted(false);
        jbtnBuscarTipoProduto.setFocusable(false);
        jbtnBuscarTipoProduto.setMargin(new java.awt.Insets(2, 4, 1, 4));
        jbtnBuscarTipoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarTipoProdutoActionPerformed(evt);
            }
        });

        jbtnNovoTipoProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add.png"))); // NOI18N
        jbtnNovoTipoProduto.setToolTipText("Cadastrar Novo Tipo de Produto");
        jbtnNovoTipoProduto.setFocusPainted(false);
        jbtnNovoTipoProduto.setFocusable(false);
        jbtnNovoTipoProduto.setMargin(new java.awt.Insets(2, 4, 1, 4));
        jbtnNovoTipoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNovoTipoProdutoActionPerformed(evt);
            }
        });

        jtfDescricao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfDescricao.setToolTipText("Descrição do Produto");
        jtfDescricao.setMargin(new java.awt.Insets(2, 1, 2, 1));

        javax.swing.GroupLayout jpGeralLayout = new javax.swing.GroupLayout(jpGeral);
        jpGeral.setLayout(jpGeralLayout);
        jpGeralLayout.setHorizontalGroup(
            jpGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGeralLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jpGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpGeralLayout.createSequentialGroup()
                        .addGroup(jpGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlValor)
                            .addComponent(jlTipoDoProduto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpGeralLayout.createSequentialGroup()
                                .addComponent(jtfTipoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnBuscarTipoProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnNovoTipoProduto))
                            .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jlDescricaoDoProduto)
                    .addComponent(jtfDescricao))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jpGeralLayout.setVerticalGroup(
            jpGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGeralLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jpGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnBuscarTipoProduto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlTipoDoProduto)
                        .addComponent(jtfTipoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnNovoTipoProduto)))
                .addGap(18, 18, 18)
                .addGroup(jpGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlValor)
                    .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jlDescricaoDoProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jpGeral, java.awt.BorderLayout.CENTER);

        jpConfirmar.setBackground(new java.awt.Color(255, 255, 255));
        jpConfirmar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 20));

        jbtnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/save.png"))); // NOI18N
        jbtnSalvar.setMnemonic('S');
        jbtnSalvar.setText("Salvar");
        jbtnSalvar.setFocusPainted(false);
        jbtnSalvar.setFocusable(false);
        jbtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalvarActionPerformed(evt);
            }
        });
        jpConfirmar.add(jbtnSalvar);

        jbtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancel.png"))); // NOI18N
        jbtnCancelar.setMnemonic('C');
        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.setFocusPainted(false);
        jbtnCancelar.setFocusable(false);
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });
        jpConfirmar.add(jbtnCancelar);

        getContentPane().add(jpConfirmar, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void initProduto() {
        if (produto != null) {
            tipoProduto = produto.getTipoProduto();
            jtfTipoProduto.setText(tipoProduto.getDescricao());
            jtfValor.setText(String.valueOf(produto.getValor()));
            jtfDescricao.setText(produto.getDescricao());
        }
    }
        
    private boolean camposEstaoVazios() {
        String descricao = jtfDescricao.getText().replace(" ", "");
        String valor = jtfValor.getText().replace(" ", "");
        return cadastrar && tipoProduto == null && descricao.isEmpty() && valor.isEmpty();
    }
    
    private void showQuitDialog() {
        String mensagem = cadastrar ? "Você realmente deseja cancelar o cadastro do produto?" : "Você realmente deseja cancelar a edição dos dados do produto?";
        if (camposEstaoVazios() || JOptionPane.showConfirmDialog(this, mensagem, "Confirmação", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }
    
    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        showQuitDialog();
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        showQuitDialog();
    }//GEN-LAST:event_formWindowClosing

    private void jbtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalvarActionPerformed
        String valor = jtfValor.getText().trim().replace(",", ".");
        String descricao = jtfDescricao.getText().trim();
        
        if (produto == null) {
            produto = new Produto();
        }

        if (tipoProduto == null) {
            JOptionPane.showMessageDialog(this, "Você deve informar o tipo do produto!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            produto.setTipoProduto(tipoProduto);
        }
        
        if (valor.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Você deve informar o valor do produto!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (!Validar.numero(valor) || Double.parseDouble(valor) < 0) {
            JOptionPane.showMessageDialog(this, "O valor informado do produto não é valido!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            produto.setValor(Double.parseDouble(valor));
        }
        
        
        if (descricao.length() < 3) {
            JOptionPane.showMessageDialog(this, "Você deve informar a descrição do produto!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        } else if ((cadastrar || (produto.getDescricao() != null && !produto.getDescricao().equals(descricao))) && DAO.findEntityByColumn("descricao", descricao) != null) {
            JOptionPane.showMessageDialog(this, "Um produto já foi cadastrado com esta descrição!", "Erro", JOptionPane.ERROR_MESSAGE);
            return; 
        } else {
            produto.setDescricao(descricao);
        }
        
        try {
            if (cadastrar) {
                DAO.create(produto);
                JOptionPane.showMessageDialog(this, "Produto cadastrado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            } else {
                DAO.edit(produto);
                JOptionPane.showMessageDialog(this, "Dados do produto editados com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            }
            if (action != null) {
                action.accept(produto);
            }
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao tentar salvar o produto!", "Erro Desconhecido", JOptionPane.ERROR_MESSAGE);
            Logger.save(e);
        }
    }//GEN-LAST:event_jbtnSalvarActionPerformed

    private void jbtnNovoTipoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNovoTipoProdutoActionPerformed
        new DialogoSalvarTipoProduto((Frame) getParent(), true, (tp) -> {
            this.tipoProduto = tp;
            this.jtfTipoProduto.setText(tp.getDescricao());
        }).setVisible(true);
    }//GEN-LAST:event_jbtnNovoTipoProdutoActionPerformed

    private void jbtnBuscarTipoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarTipoProdutoActionPerformed
        new DialogoBuscarTipoProduto((Frame) getParent(), true, (tp) -> {
            this.tipoProduto = tp;
            this.jtfTipoProduto.setText(tp.getDescricao());
        }).setVisible(true);
    }//GEN-LAST:event_jbtnBuscarTipoProdutoActionPerformed

    private void jtfValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfValorKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.' && evt.getKeyChar() != ',') {
            evt.consume();
        }
    }//GEN-LAST:event_jtfValorKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnBuscarTipoProduto;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnNovoTipoProduto;
    private javax.swing.JButton jbtnSalvar;
    private javax.swing.JLabel jlDescricaoDoProduto;
    private javax.swing.JLabel jlTipoDoProduto;
    private javax.swing.JLabel jlValor;
    private javax.swing.JPanel jpConfirmar;
    private javax.swing.JPanel jpGeral;
    private javax.swing.JTextField jtfDescricao;
    private javax.swing.JTextField jtfTipoProduto;
    private javax.swing.JFormattedTextField jtfValor;
    // End of variables declaration//GEN-END:variables

}